name: chart-function pipeline
trigger:
  branches:
    include:
      - refs/tags/*
pr:
  branches:
    include:
      - master

resources:
  repositories:
    - repository: cnp-azuredevops-libraries
      type: github
      ref: refs/heads/dtspo-34311-upgrade-helm-validation-pl-v4
      name: hmcts/cnp-azuredevops-libraries
      endpoint: 'hmcts'

variables:
  - template: vars/helm-unittest-variables.yaml@cnp-azuredevops-libraries

parameters:
  - name: validationJobs
    type: object
    default:
      - jobName: ValidateServiceBus
        chartReleaseName: chart-function-ci-servicebus-test
        valuesFile: ci-values-servicebus.yaml
        kubeconformValuesFile: ci-values-servicebus.yaml
        runUnitTests: true
        helmUnittestFile: servicebus_trigger_test.yaml
        helmUnittestValuesFiles:
          - "ci-values-servicebus.yaml"
      - jobName: ValidateBlob
        chartReleaseName: chart-function-ci-blob-test
        valuesFile: ci-values-blob.yaml
        kubeconformValuesFile: ci-values-blob.yaml
        runUnitTests: true
        helmUnittestFile: blob_trigger_test.yaml
        helmUnittestValuesFiles:
          - "ci-values-blob.yaml"
      - jobName: ValidateMixed
        chartReleaseName: chart-function-ci-mixed-test
        valuesFile: ci-values-mixed.yaml
        kubeconformValuesFile: ci-values-mixed.yaml
        runUnitTests: true
        helmUnittestFile: mixed_trigger_test.yaml
        helmUnittestValuesFiles:
          - "ci-values-mixed.yaml"
      - jobName: ValidateAzuredevopstrigger
        chartReleaseName: chart-function-ci-azure-pipelines-test
        valuesFile: ci-values-azure-pipelines.yaml
        kubeconformValuesFile: ci-values-azure-pipelines.yaml
        runUnitTests: true
        helmUnittestFile: azure_pipelines_trigger_test.yaml
        helmUnittestValuesFiles:
          - "ci-values-azure-pipelines.yaml"
      - jobName: ValidatePostgrestrigger
        chartReleaseName: chart-function-ci-postgres-test
        valuesFile: ci-values-postgres.yaml
        kubeconformValuesFile: ci-values-postgres.yaml
        runUnitTests: true
        helmUnittestFile: postgres_trigger_test.yaml
        helmUnittestValuesFiles:
          - "ci-values-postgres.yaml"
      - jobName: ValidateScaledJob
        chartReleaseName: chart-function-ci-scaledjob-test
        valuesFile: ci-values-scaledjob.yaml
        kubeconformValuesFile: ci-values-scaledjob.yaml
        runUnitTests: true
        helmUnittestFile: scaledjob_test.yaml
        helmUnittestValuesFiles:
          - "ci-values-scaledjob.yaml"
        runSnapshotTests: true
      - jobName: ValidateScaledObject
        chartReleaseName: chart-function-ci-scaledobject-test
        valuesFile: ci-values-scaledobject.yaml
        kubeconformValuesFile: ci-values-scaledobject.yaml
        runUnitTests: true
        helmUnittestFile: scaledobject_test.yaml
        helmUnittestValuesFiles:
          - "ci-values-scaledobject.yaml"
      - jobName: ValidateTriggerAuth
        chartReleaseName: chart-function-ci-triggerauth-test
        valuesFile: ci-values-triggerAuth.yaml
        kubeconformValuesFile: ci-values-triggerAuth.yaml
        runUnitTests: true
        helmUnittestFile: triggerauthentication_test.yaml
        helmUnittestValuesFiles:
          - "ci-values-triggerAuth.yaml"

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - ${{ each validateJob in parameters.validationJobs }}:
    - job: ${{ validateJob.jobName }}
      steps:
        - template: steps/charts/validate.yaml@cnp-azuredevops-libraries
          parameters:
            chartName: function
            chartReleaseName: ${{ validateJob.chartReleaseName }}
            chartNamespace: chart-tests
            helmInstallTimeout: "500"
            valuesFile: ${{ validateJob.valuesFile }}
            kubeconformValuesFile: ${{ validateJob.kubeconformValuesFile }}
            runUnitTests: ${{ validateJob.runUnitTests }}
            helmUnittestFile: ${{ validateJob.helmUnittestFile }}
            helmUnittestValuesFiles: ${{ validateJob.helmUnittestValuesFiles }}
            runSnapshotTests: ${{ eq(validateJob.runSnapshotTests, true) }}

  - job: Release
    # Make sure we have a tag to run this job
    condition: >
      and(
          succeeded(),
          startsWith(variables['Build.SourceBranch'], 'refs/tags/')
        )
    dependsOn:
      - ValidateServiceBus
      - ValidateBlob
      - ValidateMixed
      - ValidateAzuredevopstrigger
      - ValidatePostgrestrigger
      - ValidateScaledJob
      - ValidateScaledObject
      - ValidateTriggerAuth
    steps:
      - template: steps/charts/release.yaml@cnp-azuredevops-libraries
        parameters:
          chartName: function
          chartReleaseName: chart-function
          chartNamespace: chart-tests
