name: chart-function pipeline
trigger:
  branches:
    include:
      - refs/tags/*
pr:
  branches:
    include:
      - master
resources:
  repositories:
    - repository: cnp-azuredevops-libraries
      type: github
      ref: refs/heads/master
      name: hmcts/cnp-azuredevops-libraries
      endpoint: 'hmcts'
      
pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: ValidateServiceBus
    steps:
      - template: steps/charts/validate.yaml@cnp-azuredevops-libraries
        parameters:
          chartName: function
          chartReleaseName: chart-function-ci-servicebus-test
          chartNamespace: chart-tests
          helmInstallTimeout: "500"
          valuesFile: ci-values-servicebus.yaml

  - job: ValidateBlob
    steps:
      - template: steps/charts/validate.yaml@cnp-azuredevops-libraries
        parameters:
          chartName: function
          chartReleaseName: chart-function-ci-blob-test
          chartNamespace: chart-tests
          helmInstallTimeout: "500"
          valuesFile: ci-values-blob.yaml

  - job: ValidateBlobUsingReleaseName
    steps:
      - template: steps/charts/validate.yaml@cnp-azuredevops-libraries
        parameters:
          chartName: function
          chartReleaseName: chart-function-ci-blob-rn-test
          chartNamespace: chart-tests
          helmInstallTimeout: "500"
          valuesFile: ci-values-blob-release-name.yaml

  - job: ValidateMixed
    steps:
      - template: steps/charts/validate.yaml@cnp-azuredevops-libraries
        parameters:
          chartName: function
          chartReleaseName: chart-function-ci-mixed-test
          chartNamespace: chart-tests
          helmInstallTimeout: "500"
          valuesFile: ci-values-mixed.yaml
  - job: ValidateAzuredevopstrigger
    steps:
      - template: steps/charts/validate.yaml@cnp-azuredevops-libraries
        parameters:
          chartName: function
          chartReleaseName: chart-function-ci-azure-pipelines-test
          chartNamespace: chart-tests
          helmInstallTimeout: "500"
          valuesFile: ci-values-azure-pipelines.yaml
  - job: ValidatePostgrestrigger
    steps:
      - template: steps/charts/validate.yaml@cnp-azuredevops-libraries
        parameters:
          chartName: function
          chartReleaseName: chart-function-ci-postgres-test
          chartNamespace: chart-tests
          helmInstallTimeout: "500"
          valuesFile: ci-values-postgres.yaml

  - job: Release
    # Make sure we have a tag to run this job
    condition: >
      and(
          succeeded(),
          startsWith(variables['Build.SourceBranch'], 'refs/tags/')
        )
    dependsOn:
      - ValidateServiceBus
      - ValidateBlob
    steps:
      - template: steps/charts/release.yaml@cnp-azuredevops-libraries
        parameters:
          chartName: function
          chartReleaseName: chart-function
          chartNamespace: chart-tests