parameters:
  - name: serviceConnection
    displayName: Service Connection
    type: string
    default: 'DCD-CFTAPPS-DEV' # DCD-CFTAPPS-DEV
  - name: aksResourceGroup
    displayName: AKS Resource Group
    type: string
    default: 'cft-preview-01-rg' # cft-preview-00-rg
  - name: aksCluster
    displayName: AKS Cluster Name
    type: string
    default: 'cft-preview-01-aks' # cft-preview-00-aks

name: chart-function pipeline
trigger:
  branches:
    include:
      - refs/tags/*
pr:
  branches:
    include:
      - master
resources:
  repositories:
    - repository: cnp-library
      type: github
      ref: refs/heads/master
      name: hmcts/cnp-azuredevops-libraries
      endpoint: 'hmcts'

jobs:
  - job: ValidateServiceBus
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - template: steps/charts/validate.yaml@cnp-library
        parameters:
          chartName: function
          chartReleaseName: chart-function-ci-servicebus-test
          chartNamespace: chart-tests
          helmInstallTimeout: "500"
          valuesFile: ci-values-servicebus.yaml
          serviceConnection: ${{ parameters.serviceConnection }}
          aksResourceGroup: ${{ parameters.aksResourceGroup }}
          aksCluster: ${{ parameters.aksCluster }}

  - job: ValidateBlob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - template: steps/charts/validate.yaml@cnp-library
        parameters:
          chartName: function
          chartReleaseName: chart-function-ci-blob-test
          chartNamespace: chart-tests
          helmInstallTimeout: "500"
          valuesFile: ci-values-blob.yaml
          serviceConnection: ${{ parameters.serviceConnection }}
          aksResourceGroup: ${{ parameters.aksResourceGroup }}
          aksCluster: ${{ parameters.aksCluster }}

  - job: ValidateBlobUsingReleaseName
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - template: steps/charts/validate.yaml@cnp-library
        parameters:
          chartName: function
          chartReleaseName: chart-function-ci-blob-test
          chartNamespace: chart-tests
          helmInstallTimeout: "500"
          valuesFile: ci-values-blob-release-name.yaml
          serviceConnection: ${{ parameters.serviceConnection }}
          aksResourceGroup: ${{ parameters.aksResourceGroup }}
          aksCluster: ${{ parameters.aksCluster }}

  - job: ValidateMixed
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - template: steps/charts/validate.yaml@cnp-library
        parameters:
          chartName: function
          chartReleaseName: chart-function-ci-mixed-test
          chartNamespace: chart-tests
          helmInstallTimeout: "500"
          valuesFile: ci-values-mixed.yaml
          serviceConnection: ${{ parameters.serviceConnection }}
          aksResourceGroup: ${{ parameters.aksResourceGroup }}
          aksCluster: ${{ parameters.aksCluster }}

  - job: Release
    # Make sure we have a tag to run this job
    condition: >
      and(
          succeeded(),
          startsWith(variables['Build.SourceBranch'], 'refs/tags/')
        )
    dependsOn:
      - ValidateServiceBus
      - ValidateBlob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - template: steps/charts/release.yaml@cnp-library
        parameters:
          chartName: function
          chartReleaseName: chart-function
          chartNamespace: chart-tests