name: chart-function pipeline
trigger:
  branches:
    include:
      - refs/tags/*
pr:
  branches:
    include:
      - master
resources:
  repositories:
    - repository: cnp-library
      type: github
      ref: refs/heads/master
      name: hmcts/cnp-azuredevops-libraries
      endpoint: 'hmcts'

jobs:
  - job: ValidateServiceBus
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
      - template: steps/charts/validate.yaml@cnp-library
        parameters:
          chartName: function
          chartReleaseName: chart-function-ci-servicebus-test
          chartNamespace: chart-tests
          helmInstallTimeout: "500"
          valuesFile: ci-values-servicebus.yaml

  - job: ValidateBlob
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
      - template: steps/charts/validate.yaml@cnp-library
        parameters:
          chartName: function
          chartReleaseName: chart-function-ci-blob-test
          chartNamespace: chart-tests
          helmInstallTimeout: "500"
          valuesFile: ci-values-blob.yaml

  - job: ValidateBlobUsingReleaseName
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
      - template: steps/charts/validate.yaml@cnp-library
        parameters:
          chartName: function
          chartReleaseName: chart-function-ci-blob-test
          chartNamespace: chart-tests
          helmInstallTimeout: "500"
          valuesFile: ci-values-blob-release-name.yaml

  - job: ValidateMixed
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
      - template: steps/charts/validate.yaml@cnp-library
        parameters:
          chartName: function
          chartReleaseName: chart-function-ci-mixed-test
          chartNamespace: chart-tests
          helmInstallTimeout: "500"
          valuesFile: ci-values-mixed.yaml

  - job: Release
    # Make sure we have a tag to run this job
    condition: >
      and(
          succeeded(),
          startsWith(variables['Build.SourceBranch'], 'refs/tags/')
        )
    dependsOn:
      - ValidateServiceBus
      - ValidateBlob
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
      - template: steps/charts/release.yaml@cnp-library
        parameters:
          chartName: function
          chartReleaseName: chart-function
          chartNamespace: chart-tests