name: chart-function pipeline
trigger:
  branches:
    include:
      - refs/tags/*
pr:
  branches:
    include:
      - master

resources:
  repositories:
    - repository: cnp-azuredevops-libraries
      type: github
      ref: refs/heads/master
      name: hmcts/cnp-azuredevops-libraries
      endpoint: 'hmcts'

parameters:
  - name: validationJobs
    type: object
    default:
      - jobName: ValidateServiceBus
        chartReleaseName: chart-function-ci-servicebus-test
        valuesFile: ci-values-servicebus.yaml
        kubeconformValuesFile: ci-values-servicebus.yaml
        runUnitTests: true
        unitTestFile: servicebus_trigger_test.yaml
        helmUnittestValuesFile: ci-values-servicebus.yaml
      - jobName: ValidateBlob
        chartReleaseName: chart-function-ci-blob-test
        valuesFile: ci-values-blob.yaml
        kubeconformValuesFile: ci-values-blob.yaml
        runUnitTests: true
        unitTestFile: blob_trigger_test.yaml
        helmUnittestValuesFile: ci-values-blob.yaml
      - jobName: ValidateMixed
        chartReleaseName: chart-function-ci-mixed-test
        valuesFile: ci-values-mixed.yaml
        kubeconformValuesFile: ci-values-mixed.yaml
        runUnitTests: true
        unitTestFile: mixed_trigger_test.yaml
        helmUnittestValuesFile: ci-values-mixed.yaml
      - jobName: ValidateAzuredevopstrigger
        chartReleaseName: chart-function-ci-azure-pipelines-test
        valuesFile: ci-values-azure-pipelines.yaml
        kubeconformValuesFile: ci-values-azure-pipelines.yaml
        runUnitTests: true
        unitTestFile: azure_pipelines_trigger_test.yaml
        helmUnittestValuesFile: ci-values-azure-pipelines.yaml
      - jobName: ValidatePostgrestrigger
        chartReleaseName: chart-function-ci-postgres-test
        valuesFile: ci-values-postgres.yaml
        kubeconformValuesFile: ci-values-postgres.yaml
        runUnitTests: true
        unitTestFile: postgres_trigger_test.yaml
        helmUnittestValuesFile: ci-values-postgres.yaml
      - jobName: ValidateTriggerAuth
        chartReleaseName: chart-function-ci-triggerAuth-test
        valuesFile: ci-values-triggerAuth.yaml
        kubeconformValuesFile: ci-values-triggerAuth.yaml
        runUnitTests: true
        unitTestFile: triggerauthentication_test.yaml
        helmUnittestValuesFile: ci-values-triggerAuth.yaml

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - ${{ each validateJob in parameters.validationJobs }}:
    - job: ${{ validateJob.jobName }}
      steps:
        - template: steps/charts/validate.yaml@cnp-azuredevops-libraries
          parameters:
            chartName: function
            chartReleaseName: ${{ validateJob.chartReleaseName }}
            chartNamespace: chart-tests
            helmInstallTimeout: "500"
            valuesFile: ${{ validateJob.valuesFile }}
            kubeconformValuesFile: ${{ validateJob.kubeconformValuesFile }}
            runUnitTests: ${{ validateJob.runUnitTests }}
            unitTestFile: ${{ validateJob.unitTestFile }}
            helmUnittestValuesFile: ${{ validateJob.helmUnittestValuesFile }}

  - job: Release
    # Make sure we have a tag to run this job
    condition: >
      and(
          succeeded(),
          startsWith(variables['Build.SourceBranch'], 'refs/tags/')
        )
    dependsOn:
      - ValidateServiceBus
      - ValidateBlob
      - ValidateMixed
      - ValidateAzuredevopstrigger
      - ValidatePostgrestrigger
    steps:
      - template: steps/charts/release.yaml@cnp-azuredevops-libraries
        parameters:
          chartName: function
          chartReleaseName: chart-function
          chartNamespace: chart-tests
