image: hmctspublic.azurecr.io/plum/batch:latest
scaleType: Job
triggers:
  - type: azure-pipelines
    poolID: "22"
    organizationURLFromEnv: "AZP_URL"
    personalAccessTokenFromEnv: "AZP_TOKEN"
    targetPipelinesQueueLength: "1"
    activationTargetPipelinesQueueLength: "5"
environment:
  TEST_ENV: "test"