image: hmctspublic.azurecr.io/plum/batch:latest
triggerAuth:
  enabled: true
  create: true
triggers:
  - type: azure-servicebus
    # Required: queueName OR topicName and subscriptionName
    queueName: test-queue
    namespace: test-namespace
    queueLength: 5
environment:
  TEST_ENV: "test"