# using Pod Identity.
image: hmctspublic.azurecr.io/plum/batch:latest
scaleType: Job
triggerAuth:
  create: true
  enabled: true
  triggerPodIdentityProvider: "azure-workload"
triggers:
  - type: azure-blob
    blobContainerName: test-functions-blob
    blobCount: 1
    accountName: "testaccount{{ .Values.global.environment }}"
environment:
  TEST_ENV: "test"
