image: hmctspublic.azurecr.io/plum/batch:latest
triggers:
  - type: azure-blob
    # Required: blobContainerName and connection
    blobContainerName: test-functions-blob # Required: Name of Azure Blob Storage container
    blobCount: 1 # Optional. Amount of blobs to scale out on. Default: 5 blobs
    accountName: "testaccount"
    blobPrefix: "" # Optional. Prefix for the Blob. Use this to specifiy sub path for the blobs if required. Default : ""
    blobDelimiter: "/" # Optional. Delimiter for identifying the blob Prefix. Default: "/"
    triggerAuthName: "azure-mi-auth-test"
    triggerPodIdentity: "azure"
environment:
  TEST_ENV: "test"