useInterpodAntiAffinity: false
name: azure-devops-agent-test
memoryRequests: 256Mi
cpuRequests: 250m
memoryLimits: 1Gi
cpuLimits: 1
devmemoryRequests: 256Mi
devcpuRequests: 250m
devmemoryLimits: 1Gi
devcpuLimits: 1
imagePullPolicy: IfNotPresent
restartPolicy: OnFailure
dnsConfig:
  ndots: "3"
global:
  enableKeyVaults: false
  environment: prod
scaleType: job
saEnabled: true
job:
  parallelism: 1 # [max number of desired pods](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#controlling-parallelism)
  completions: 1 # [desired number of successfully finished pods](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#controlling-parallelism)
  activeDeadlineSeconds: 600 # Specifies the duration in seconds relative to the startTime that the job may be active before the system tries to terminate it; value must be positive integer
  backoffLimit: 6 # Specifies the number of retries before marking this job failed. Defaults to 6
pollingInterval: 30  # Optional. Default: 30 seconds
cooldownPeriod:  300 # Optional. Default: 300 seconds
minReplicaCount: 0   # Optional. Default: 0
maxReplicaCount: 5 # Optional. Default: 5
spotInstances:
  enabled: false
triggerAuth:
  create: true
  enabled: false
  nameOverride: ""
  triggerPodIdentityProvider: "azure-workload" # none | azure | gcp | spiffe | aws-eks | aws-kiam
triggers: []
rollout:
  strategy: gradual # Default strategy deletes the running jobs when the job spec changes
  propagationPolicy: background
scalingStrategy: "default" # "default" or "accurate" supported only
useWorkloadIdentity: true
