{{- if eq .Values.scaleType "Object" }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ template "hmcts.releasename.v2" . }}
  {{- ( include "hmcts.labels.v2" . ) | indent 2 }}
spec:
  scaleTargetRef:
    apiVersion: {{ .Values.object.apiVersion | default "apps/v1" }}
    kind: {{ .Values.object.kind | default "Deployment" }}
    name: {{ required "object.name is required for ScaledObject" .Values.object.name }}
    {{- with .Values.object.envSourceContainerName }}
    envSourceContainerName: {{ . }}
    {{- end }}
  pollingInterval: {{ .Values.object.pollingInterval | default 30 }}
  cooldownPeriod: {{ .Values.object.cooldownPeriod | default 300 }}
  {{- with .Values.object.idleReplicaCount }}
  idleReplicaCount: {{ . }}
  {{- end }}
  minReplicaCount: {{ .Values.object.minReplicaCount | default 0 }}
  maxReplicaCount: {{ .Values.object.maxReplicaCount | default 100 }}
  {{- if or .Values.object.failureThreshold .Values.object.replicas }}
  fallback:
    failureThreshold: {{ .Values.object.failureThreshold | default 3 }}
    replicas: {{ .Values.object.replicas | default 1 }}
  {{- end }}
  triggers:
    {{- range .Values.triggers }}
      {{- $data := dict "root" $ "trigger" . }}
      {{- if eq .type "azure-servicebus" }}
{{- include "function.servicebus" $data | indent 4 }}
      {{- else if eq .type "azure-blob" }}
{{- include "function.blob" $data | indent 4 }}
      {{- else if eq .type "azure-pipelines" }}
{{- include "function.azure-pipelines" $data | indent 4 }}
      {{- else if eq .type "postgres" }}
{{- include "function.postgres" $data | indent 4 }}
      {{- end }}
    {{- end }}
{{- end }}
