{{- if eq .Values.trigger.blob.connection "" }}
apiVersion: keda.k8s.io/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-blob-auth
spec:
  podIdentity:
    provider: azure
---
{{- end }}
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: {{ template "hmcts.releasename.v1" . }}
spec:
  scaleType: {{ .Values.scaleType }}
  pollingInterval: {{ .Values.pollingInterval }}
  cooldownPeriod:  {{ .Values.cooldownPeriod }}
  minReplicaCount: {{ .Values.minReplicaCount }}
  maxReplicaCount: {{ .Values.maxReplicaCount }}
  jobTargetRef:
    parallelism: {{ .Values.job.parallelism }}
    completions: {{ .Values.job.completions }}
    activeDeadlineSeconds: {{ .Values.job.activeDeadlineSeconds }}
    backoffLimit: {{ .Values.job.backoffLimit }}
{{ include "hmcts.podtemplate.v1.tpl" . | indent 4 }}
  triggers:
    - type: {{ .Values.trigger.type}}
      {{- if eq .Values.trigger.type "azure-servicebus" }}
      metadata:
        {{- if .Values.trigger.servicebus.queueName }}
        queueName: {{ .Values.trigger.servicebus.queueName }}
        {{- end }}
        {{- if .Values.trigger.servicebus.topicName }}
        topicName: {{ .Values.trigger.servicebus.topicName }}
        subscriptionName: {{ .Values.trigger.servicebus.subscriptionName }}
        {{- end }}
        connection: {{ .Values.trigger.servicebus.connection }}
        queueLength: {{ .Values.trigger.servicebus.queueLength | quote }}
      {{- else if eq .Values.trigger.type "azure-blob" }}
      metadata:
        blobContainerName: {{ .Values.trigger.blob.blobContainerName }}
        blobCount: {{ .Values.trigger.blob.blobCount | quote }}
        {{- if ne .Values.trigger.blob.connection "" }}
        connection: {{ .Values.trigger.blob.connection }}
        {{- end }}
        accountName: {{ .Values.trigger.blob.accountName | quote }}
        blobPrefix: {{ .Values.trigger.blob.blobPrefix | quote }}
        blobDelimiter: {{ .Values.trigger.blob.blobDelimiter }}
      {{- end }}
      {{- if eq .Values.trigger.blob.connection "" }}
      authenticationRef:
        name: azure-blob-auth # authenticationRef would need either podIdentity or define a connection parameter
      {{- end }}