{{- if eq .Values.scaleType "Job" }}
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: {{ template "hmcts.releasename.v2" . }}
  {{- ( include "hmcts.labels.v2" . ) | indent 2 }}
spec:
  pollingInterval: {{ .Values.pollingInterval }}
  maxReplicaCount: {{ .Values.maxReplicaCount }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  rollout:
    strategy: {{ .Values.rollout.strategy }}
    propagationPolicy: {{ .Values.rollout.strategy }}
{{- if eq .Values.scalingStrategy "accurate" }}
  scalingStrategy:
    strategy: {{ .Values.scalingStrategy }}
{{- end }}
  jobTargetRef:
    parallelism: {{ .Values.job.parallelism }}
    completions: {{ .Values.job.completions }}
    activeDeadlineSeconds: {{ .Values.job.activeDeadlineSeconds }}
    backoffLimit: {{ .Values.job.backoffLimit }}
{{ include "hmcts.podtemplate.v5.tpl" . | indent 4 }}
  triggers:
    {{- range .Values.triggers }}
      {{- $data := dict "root" $ "trigger" . }}
      {{- if eq .type "azure-servicebus" }}
{{- include "function.servicebus" $data | indent 4 }}
      {{- else if eq .type "azure-blob" }}
{{- include "function.blob" $data | indent 4 }}
      {{- else if eq .type "azure-pipelines" }}
{{- include "function.azure-pipelines" $data | indent 4 }}
      {{- else if eq .type "postgres" }}
{{- include "function.postgres" $data | indent 4 }}
      {{- end }}
    {{- end }}
{{- end }}
