{{- if eq .Values.scaleType "Object" }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ template "hmcts.releasename.v2" . }}
  {{- ( include "hmcts.labels.v2" . ) | indent 2 }}
spec:
  scaleTargetRef:
    apiVersion: {{ .Values.object.apiVersion }}
    kind: {{ .Values.object.kind }}
    name: {{ .Values.object.name }}
    envSourceContainerName: {{ .Values.object.envSourceContainerName }}
  pollingInterval: {{ .Values.object.pollingInterval }}
  cooldownPeriod: {{ .Values.object.cooldownPeriod }}
  idleReplicaCount: {{ .Values.object.idleReplicaCount }}
  minReplicaCount: {{ .Values.object.minReplicaCount }}
  maxReplicaCount: {{ .Values.object.maxReplicaCount }}
  {{- if or .Values.object.failureThreshold .Values.object.replicas }}
  fallback:
    failureThreshold: {{ .Values.object.failureThreshold }}
    replicas: {{ .Values.object.replicas }}
  {{- end }}
  triggers:
    {{- range .Values.triggers }}
      {{- $data := dict "root" $ "trigger" . }}
      {{- if eq .type "azure-servicebus" }}
{{- include "function.servicebus" $data | indent 4 }}
      {{- else if eq .type "azure-blob" }}
{{- include "function.blob" $data | indent 4 }}
      {{- else if eq .type "azure-pipelines" }}
{{- include "function.azure-pipelines" $data | indent 4 }}
      {{- end }}
    {{- end }}
{{- end }}