apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: {{ template "hmcts.releasename.v2" . }}
spec:
  scaleType: {{ .Values.scaleType }}
  pollingInterval: {{ .Values.pollingInterval }}
  cooldownPeriod:  {{ .Values.cooldownPeriod }}
  minReplicaCount: {{ .Values.minReplicaCount }}
  maxReplicaCount: {{ .Values.maxReplicaCount }}
  jobTargetRef:
    parallelism: {{ .Values.job.parallelism }}
    completions: {{ .Values.job.completions }}
    activeDeadlineSeconds: {{ .Values.job.activeDeadlineSeconds }}
    backoffLimit: {{ .Values.job.backoffLimit }}
{{ include "hmcts.podtemplate.v2.tpl" . | indent 4 }}
  triggers:
    {{- range .Values.triggers }}
      {{- if eq .type "azure-servicebus" }}
{{- include "function.servicebus" . | indent 4 }}
      {{- else if eq .type "azure-blob" }}
      # work around to save having the triggerAuthName copied in the config for each trigger
      {{- $data := dict "triggerAuthName" .Values.triggerAuthName "trigger" . }}
{{- include "function.blob" $data | indent 4 }}
      {{- end }}
    {{- end }}