apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: {{ template "hmcts.releasename.v2" . }}
  {{- ( include "hmcts.labels.v2" . ) | indent 2 }}
spec:
  pollingInterval: {{ .Values.pollingInterval }}
  maxReplicaCount: {{ .Values.maxReplicaCount }}
  jobTargetRef:
    parallelism: {{ .Values.job.parallelism }}
    completions: {{ .Values.job.completions }}
    activeDeadlineSeconds: {{ .Values.job.activeDeadlineSeconds }}
    backoffLimit: {{ .Values.job.backoffLimit }}
{{ include "hmcts.podtemplate.v2.tpl" . | indent 4 }}
  triggers:
    {{- range .Values.triggers }}
      {{- $data := dict "root" $ "trigger" . }}
      {{- if eq .type "azure-servicebus" }}
{{- include "function.servicebus" $data | indent 4 }}
      {{- else if eq .type "azure-blob" }}
      # work around to save having the triggerAuthName copied in the config for each trigger
      {{- $data := dict "root" $ "trigger" . }}
{{- include "function.blob" $data | indent 4 }}
      {{- end }}
    {{- end }}