{{- if and .Values.triggerAuth.create }}
apiVersion: keda.k8s.io/v1alpha1
kind: TriggerAuthentication
metadata:
{{- include "function.trigger-auth-name" . | indent 2 }}
{{- ( include "hmcts.labels.v2" . ) | indent 2 }}
spec:
  podIdentity:
    provider: {{ .Values.triggerPodIdentityProvider }} # none | azure | gcp | spiffe | aws-eks | aws-kiam
{{- end }}